// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGA1v_CcjK3HjQFX3MRh80nvd22_9C0o',
    appId: '1:642803531468:web:485f2263913cb710b8cc69',
    messagingSenderId: '642803531468',
    projectId: 'playbot-28d85',
    authDomain: 'playbot-28d85.firebaseapp.com',
    storageBucket: 'playbot-28d85.firebasestorage.app',
    measurementId: 'G-1CJ6RS3V3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfX7XK9QYC0bG5tkZyoc2vOfqBz_uo3g',
    appId: '1:642803531468:android:3bbcdecc458d79feb8cc69',
    messagingSenderId: '642803531468',
    projectId: 'playbot-28d85',
    storageBucket: 'playbot-28d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_j5ijkJa8q6_mggt5Q6KCgeO-UmsxMo',
    appId: '1:642803531468:ios:b061106b95f14947b8cc69',
    messagingSenderId: '642803531468',
    projectId: 'playbot-28d85',
    storageBucket: 'playbot-28d85.firebasestorage.app',
    iosClientId: '642803531468-7rc9j1f6bbr8q86l88hj82huktu2o76p.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_j5ijkJa8q6_mggt5Q6KCgeO-UmsxMo',
    appId: '1:642803531468:ios:b061106b95f14947b8cc69',
    messagingSenderId: '642803531468',
    projectId: 'playbot-28d85',
    storageBucket: 'playbot-28d85.firebasestorage.app',
    iosClientId: '642803531468-7rc9j1f6bbr8q86l88hj82huktu2o76p.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMGA1v_CcjK3HjQFX3MRh80nvd22_9C0o',
    appId: '1:642803531468:web:ce5f0240b6e837a4b8cc69',
    messagingSenderId: '642803531468',
    projectId: 'playbot-28d85',
    authDomain: 'playbot-28d85.firebaseapp.com',
    storageBucket: 'playbot-28d85.firebasestorage.app',
    measurementId: 'G-E56K2147RZ',
  );
}
